// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParks.Data;

#nullable disable

namespace NationalParks.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250329054030_Remove Location from Place")]
    partial class RemoveLocationfromPlace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NationalParks.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Commission")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("Card_PK");

                    b.ToTable("Card", (string)null);
                });

            modelBuilder.Entity("NationalParks.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("Country_PK");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("NationalParks.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("Location_PK");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("NationalParks.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Coordinates")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("Location_Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Recognitions")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ReservedArea")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SiteType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("SiteTypeId")
                        .HasColumnType("int")
                        .HasColumnName("SiteType_Id");

                    b.HasKey("Id")
                        .HasName("Places_PK");

                    b.HasIndex("LocationId");

                    b.HasIndex("SiteTypeId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("NationalParks.Models.PlaceRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("int")
                        .HasColumnName("Place_Id");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PlaceRating_PK");

                    b.HasIndex("PlaceId");

                    b.ToTable("PlaceRating", (string)null);
                });

            modelBuilder.Entity("NationalParks.Models.SiteType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("SiteType_PK");

                    b.ToTable("SiteType", (string)null);
                });

            modelBuilder.Entity("NationalParks.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SpecialCharacteristics")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SpeciesType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("Species_PK");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("NationalParks.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Commission")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("int")
                        .HasColumnName("Place_Id");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date");

                    b.Property<int?>("TicketSaleId")
                        .HasColumnType("int")
                        .HasColumnName("TicketSale_Id");

                    b.HasKey("Id")
                        .HasName("Ticket_PK");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TicketSaleId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("NationalParks.Models.TicketSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("Card_Id");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.Property<int?>("VisitorId")
                        .HasColumnType("int")
                        .HasColumnName("Visitor_Id");

                    b.HasKey("Id")
                        .HasName("TicketSales_PK");

                    b.HasIndex("CardId");

                    b.HasIndex("VisitorId");

                    b.ToTable("TicketSales");
                });

            modelBuilder.Entity("NationalParks.Models.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthCountry")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("Country_Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("IdnumberOrPassport")
                        .HasColumnType("int")
                        .HasColumnName("IDNumberOrPassport");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("VisitReason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("Visitors_PK");

                    b.HasIndex("CountryId");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("PlacesXspecy", b =>
                {
                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.HasKey("SpeciesId", "PlaceId")
                        .HasName("PlacesXSpecies_PK");

                    b.HasIndex("PlaceId");

                    b.ToTable("PlacesXSpecies", (string)null);
                });

            modelBuilder.Entity("NationalParks.Models.Place", b =>
                {
                    b.HasOne("NationalParks.Models.Location", "LocationNavigation")
                        .WithMany("Places")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("PlacesXLocation_FK");

                    b.HasOne("NationalParks.Models.SiteType", "SiteTypeNavigation")
                        .WithMany("Places")
                        .HasForeignKey("SiteTypeId")
                        .HasConstraintName("SiteTypeXPlaces_FK");

                    b.Navigation("LocationNavigation");

                    b.Navigation("SiteTypeNavigation");
                });

            modelBuilder.Entity("NationalParks.Models.PlaceRating", b =>
                {
                    b.HasOne("NationalParks.Models.Place", "Place")
                        .WithMany("PlaceRatings")
                        .HasForeignKey("PlaceId")
                        .HasConstraintName("PlacesXPlaceRating_FK");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("NationalParks.Models.Ticket", b =>
                {
                    b.HasOne("NationalParks.Models.Place", "PlaceNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("PlaceId")
                        .HasConstraintName("PlacesXTickets_FK");

                    b.HasOne("NationalParks.Models.TicketSale", "TicketSale")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketSaleId")
                        .HasConstraintName("SalesXTickets_FK");

                    b.Navigation("PlaceNavigation");

                    b.Navigation("TicketSale");
                });

            modelBuilder.Entity("NationalParks.Models.TicketSale", b =>
                {
                    b.HasOne("NationalParks.Models.Card", "Card")
                        .WithMany("TicketSales")
                        .HasForeignKey("CardId")
                        .HasConstraintName("SalesXCardCommission_FK");

                    b.HasOne("NationalParks.Models.Visitor", "Visitor")
                        .WithMany("TicketSales")
                        .HasForeignKey("VisitorId")
                        .HasConstraintName("SalesXVisitors_FK");

                    b.Navigation("Card");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("NationalParks.Models.Visitor", b =>
                {
                    b.HasOne("NationalParks.Models.Country", "Country")
                        .WithMany("Visitors")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("VisitorsXCountry_FK");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PlacesXspecy", b =>
                {
                    b.HasOne("NationalParks.Models.Place", null)
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .IsRequired()
                        .HasConstraintName("PlacesXSpecies_FK2");

                    b.HasOne("NationalParks.Models.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .IsRequired()
                        .HasConstraintName("PlacesXSpecies_FK1");
                });

            modelBuilder.Entity("NationalParks.Models.Card", b =>
                {
                    b.Navigation("TicketSales");
                });

            modelBuilder.Entity("NationalParks.Models.Country", b =>
                {
                    b.Navigation("Visitors");
                });

            modelBuilder.Entity("NationalParks.Models.Location", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("NationalParks.Models.Place", b =>
                {
                    b.Navigation("PlaceRatings");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("NationalParks.Models.SiteType", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("NationalParks.Models.TicketSale", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("NationalParks.Models.Visitor", b =>
                {
                    b.Navigation("TicketSales");
                });
#pragma warning restore 612, 618
        }
    }
}
